
[server]
enableStaticServing = true

[runner]
enforceSerializableSessionState = true

[theme]
primaryColor = "#388E3C"
backgroundColor = "#333333"
secondaryBackgroundColor = "#555555"
textColor = "#FFFFFF"
font = "sans serif"
